version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9.4-management
    ports:
      - 5672:5672 # RabbitMQ porta padr√£o
      - 15672:15672 # RabbitMQ management plugin port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=iago
      - RABBITMQ_DEFAULT_PASS=123123
volumes:
  rabbitmq_data:
